on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  test-trigger:
    runs-on: libch-self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: khan/pull-request-comment-trigger@master
      - name: Pull Request Comment Trigger
        # You may pin to the exact commit or the version.
        # uses: Khan/pull-request-comment-trigger@af6260d48c05e1f2f1641f9d14794bd04687c023
        uses: Khan/pull-request-comment-trigger@1.0.0
        with:
          # The emoji "reaction" to put on the comment to indicate that the trigger was detected. For example, "rocket"
          reaction: 'rocket'# optional
          # The string to look for in pull-request descriptions and comments. For example "#build/android"
          trigger: '#testch'
